### ISSUE TITLE
Blank window when I click on join another room

### ISSUE THREAD

**Issue by dpascu** [hfellerhoff/listentogether-hackathon#1]
Hi @hfellerhoff , congratulations on the idea. It's really fun.

Anyway, I was trying the app with a friend and when any of us connected and clicked on join a room, it goes blank.

Here's a screenshot of the console after that:
![image](https://user-images.githubusercontent.com/5720424/85680364-863cc500-b6ca-11ea-84bc-57dcbcd7ad1a.png)

**Comment by hfellerhoff** [comment]
Hey @dpascu, thanks for reaching out and posting an issue! I really appreciate it.

I was having trouble replicating the issue, but I found where it was happening and there are now better null/undefined checks in place to make sure that doesn't happen again.

Let me know if that fixes the issue!
